version: '2.1'
networks:
  quorum_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
services:
  quorum_1:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 22001:22000
    environment:
      - CONSTELLATION_PUB=BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=
      - CONSTELLATION_KEY={"data":{"bytes":"Wl+xSyXVuuqzpvznOS7dOobhcn4C5auxkFRi7yLtgtA="},"type":"unlocked"}
      - NODEKEY=2592481e30cc38206076ecfdf67f8446991f199a6e403ae8bf190b9f3c9d613a
      - BOOTNODE_IP=172.19.1.1
    volumes:
      - ./data/nodes.json:/root/.ethereum/permissioned-nodes.json
      - ./data/nodes.json:/root/.ethereum/static-nodes.json
    networks:
      quorum_net:
        ipv4_address: '172.19.1.1'
  quorum_2:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 22002:22000
    volumes:
      - ./data/nodes.json:/root/.ethereum/permissioned-nodes.json
      - ./data/nodes.json:/root/.ethereum/static-nodes.json
    environment:
      - CONSTELLATION_PUB=QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=
      - CONSTELLATION_KEY={"data":{"bytes":"nDFwJNHSiT1gNzKBy9WJvMhmYRkW3TzFUmPsNzR6oFk="},"type":"unlocked"}
      - NODEKEY=dae4fb95513713d0f60e588851ca8f5c5d82688c1c7d67f32e8bfedddb118b74
      - BOOTNODE_IP=172.19.1.1
    networks:
      quorum_net:
        ipv4_address: '172.19.1.2'
  quorum_3:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 22003:22000
    volumes:
      - ./data/nodes.json:/root/.ethereum/permissioned-nodes.json
      - ./data/nodes.json:/root/.ethereum/static-nodes.json
    environment:
      - CONSTELLATION_PUB=1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=
      - CONSTELLATION_KEY={"data":{"bytes":"tMxUVR8bX7aq/TbpVHc2QV3SN2iUuExBwefAuFsO0Lg="},"type":"unlocked"}
      - NODEKEY=a2c301dabbd3c53c8337acb96e979a56abb9df23f7102faf78ec3e3ffea7dfcf
      - BOOTNODE_IP=172.19.1.1
    networks:
      quorum_net:
        ipv4_address: '172.19.1.3'
  quorum_4:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 22004:22000
    volumes:
      - ./data/nodes.json:/root/.ethereum/permissioned-nodes.json
      - ./data/nodes.json:/root/.ethereum/static-nodes.json
    environment:
      - CONSTELLATION_PUB=R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=
      - CONSTELLATION_KEY={"data":{"bytes":"W8XcdJfOuxCrLcspSceNg9vh7Cwe8tXiIx5xPJ88OtQ="},"type":"unlocked"}
      - NODEKEY=c3e8ecba5f9ae5e4441109b5c94c102e201b8f739b0d814f861e1b87732fa59b
      - BOOTNODE_IP=172.19.1.1
    networks:
      quorum_net:
        ipv4_address: '172.19.1.4'
